import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Julu 2</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/programandoconmei/image/upload/v1663450751/JULU_ocgbye.ico"
        />
      </Head>

      <Header />

      <Nav />
    </div>
  );
}
